# This is sample demo file which only print the msg on local machine..
---
- name: Test Ansible setup
  hosts: localhost
  tasks:
    - name: Print message
      debug:
        msg: "Ansible AU294 working on RHEL 10!"
...

